import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Booking terms | TTD Studio", robots: { index: false, follow: false } };

export default async function TermsPage({ searchParams }: { searchParams: Promise<{ lang?: string }> }) {
  const language = (await searchParams).lang === "en" ? "en" : "da";
  return <LegalPage language={language} kind="terms">{language === "da" ? <Danish /> : <English />}</LegalPage>;
}

function Danish() { return <>
  <p>Disse vilkår gælder for tidsbestemt leje af TTD Studio til dans, undervisning, prøver og lignende aktiviteter. De skal læses før betaling. Billetter til særskilte events kan have egne vilkår, som vises ved det pågældende køb.</p>
  <section><h2>1. Udlejer og kontakt</h2><p>TOTAL ENTERTAINMENT, CVR-nr. 21285870, Skydebanegade 10, st., 1709 København V, e-mail <a href="mailto:booking@didde-mie.com">booking@didde-mie.com</a>, telefon [indsæt telefon]. Studiet ligger hos København Danser, Nygaardsvej 5a, 2. sal, 2100 København Ø.</p></section>
  <section><h2>2. Booking og pris</h2><p>Du vælger dato, starttid og et sammenhængende antal timer. Alle tider vises i dansk lokaltid (Europe/Copenhagen). Den samlede pris, inklusive lovpligtige afgifter og eventuelle obligatoriske gebyrer, vises før betaling. En booking er først bindende, når betalingen er godkendt, og du har modtaget en bekræftelse med bookingreference. Hvis en tid ikke længere er ledig, oprettes ingen bekræftet booking.</p><p>Betaling sker online med de betalingsmåder, der vises i checkout. Kvittering sendes til den e-mailadresse, du oplyser. Kontroller derfor adresse, dato og tidsrum før betaling.</p></section>
  <section><h2>3. Gratis afbestilling mere end 24 timer før</h2><p>Du kan afbestille din booking uden omkostninger <strong>når der er mere end 24 timer til den første bookede time</strong>. Afbestillingen gælder alle timer i bookingen. Fristen beregnes fra bookingens starttidspunkt i dansk lokaltid. Ved rettidig afbestilling får du hele det betalte beløb tilbage til den oprindelige betalingsmetode. Refusionen igangsættes, når afbestillingen er registreret; bankens eller kortudstederens behandlingstid kan variere.</p><p>Afbestilling ved 24 timer eller mindre før start samt udeblivelse giver som udgangspunkt ikke refusion. Kontakt os hurtigst muligt, hvis særlige forhold gør sig gældende; en undtagelse kræver en konkret aftale. Brug linket i bookingmailen, når selvbetjening er tilgængelig, eller skriv til <a href="mailto:booking@didde-mie.com">booking@didde-mie.com</a>. Det er tidspunktet, hvor vi modtager din afbestilling, der er afgørende. Vi bekræfter afbestillingen skriftligt.</p></section>
  <section><h2>4. Ændringer</h2><p>Du kan anmode om at ændre dato eller tidsrum, når der er mere end 24 timer til den første bookede time. En ændring afhænger af ledige tider og bekræftes særskilt. Er den nye booking dyrere, betales forskellen; er den billigere, refunderes forskellen. Kan vi ikke tilbyde den ønskede tid, kan du stadig afbestille efter punkt 3. Ved 24 timer eller mindre før start er ændringer kun mulige efter aftale.</p></section>
  <section><h2>5. Brug af studiet</h2><p>Bookingen giver adgang til det bekræftede tidsrum, herunder klargøring og oprydning. Forlad lokalet i samme ryddelige stand og senest ved sluttid. Følg stedets anvisninger, brandregler og rimelige hensyn til øvrige brugere. Aktiviteten må ikke overskride lovlige kapacitets- eller sikkerhedsgrænser. Du hæfter efter dansk rets almindelige regler for skader, som du eller dine deltagere forvolder ved ansvarspådragende adfærd. Vi opkræver ikke et automatisk standardgebyr for skade.</p></section>
  <section><h2>6. Hvis studiet ikke kan stilles til rådighed</h2><p>Hvis vi må aflyse eller ikke kan levere det aftalte tidsrum, tilbyder vi en ny ledig tid eller fuld tilbagebetaling. Dine ufravigelige rettigheder efter dansk ret berøres ikke.</p></section>
  <section><h2>7. Fortrydelsesret og klager</h2><p>Den lovbestemte 14-dages fortrydelsesret afhænger af aftalens karakter. Tidsbestemte fritidsaktiviteter kan være undtaget. Den aftalte 24-timers afbestillingsret ovenfor gælder uanset dette og indskrænker ikke rettigheder, du måtte have efter ufravigelig lovgivning.</p><p>Kontakt os først på <a href="mailto:booking@didde-mie.com">booking@didde-mie.com</a>, hvis der er et problem. Hvis vi ikke finder en løsning, kan forbrugere i relevante tilfælde klage til <a href="https://naevneneshus.dk/start-din-klage/center-for-klageloesning-og-forbrugerklagenaevnet/" target="_blank" rel="noopener noreferrer">Mæglingsteamet for Forbrugerklager, Nævnenes Hus, Toldboden 2, 8800 Viborg</a>. Om den konkrete sag kan behandles, afhænger blandt andet af ydelsen og beløbet.</p></section>
  <section><h2>8. Personoplysninger og ændringer af vilkår</h2><p>Se vores <a href="/privacy?lang=da">privatlivspolitik</a> for behandling af bookingoplysninger. De vilkår, der vises ved din betaling, gælder for den booking. Ændringer på denne side gælder kun fremtidige bookinger.</p></section>
</>; }

function English() { return <>
  <p>These terms apply to bookings of TTD Studio for dance, teaching, rehearsal and similar activities at a specified time. Read them before paying. Separate events may have their own ticket terms shown at checkout.</p>
  <section><h2>1. Provider and contact</h2><p>TOTAL ENTERTAINMENT, Danish business registration no. (CVR) 21285870, Skydebanegade 10, st., 1709 København V, Denmark, email <a href="mailto:booking@didde-mie.com">booking@didde-mie.com</a>, phone [insert phone]. The studio is at København Danser, Nygaardsvej 5a, 2nd floor, 2100 Copenhagen Ø.</p></section>
  <section><h2>2. Booking and price</h2><p>Choose a date, start time and consecutive hours. All times use Copenhagen local time (Europe/Copenhagen). The total price, including applicable taxes and mandatory fees, is shown before payment. A booking becomes binding only after payment is approved and you receive a confirmation with a booking reference. No confirmed booking is created if a slot is no longer available.</p><p>Pay online using the methods shown at checkout. We email a receipt to the address you provide. Check your email, date and time before paying.</p></section>
  <section><h2>3. Free cancellation more than 24 hours before</h2><p>You may cancel your booking free of charge <strong>when more than 24 hours remain before the first booked hour starts</strong>. Cancellation applies to every hour in the booking. The cutoff is calculated from the booking start in Copenhagen local time. A timely cancellation gives a full refund to the original payment method. We initiate the refund after recording the cancellation; your bank or card issuer may take additional time to process it.</p><p>A cancellation at 24 hours or less before the start, or a no-show, normally has no refund. Contact us promptly about exceptional circumstances; an exception requires a specific agreement. Use the link in your booking email when self-service is available, or email <a href="mailto:booking@didde-mie.com">booking@didde-mie.com</a>. The time we receive your cancellation determines whether it is in time. We confirm the cancellation in writing.</p></section>
  <section><h2>4. Changes</h2><p>You may request a change of date or time when more than 24 hours remain before the first booked hour. Changes depend on availability and require separate confirmation. Pay any increase in price; we refund any decrease. If the requested time is unavailable, you may still cancel under section 3. At 24 hours or less before the start, changes require individual agreement.</p></section>
  <section><h2>5. Using the studio</h2><p>Your booked time includes setup and tidying. Leave the room tidy and by the end time. Follow venue instructions, fire safety rules and reasonable consideration for other users. Activities must stay within lawful occupancy and safety limits. You are liable under ordinary Danish law for damage caused by your or your participants' negligent or wrongful conduct. We do not impose an automatic standard damage fee.</p></section>
  <section><h2>6. If we cannot provide the studio</h2><p>If we cancel or cannot provide the agreed time, we offer another available time or a full refund. Your mandatory rights under Danish law remain unaffected.</p></section>
  <section><h2>7. Statutory withdrawal and complaints</h2><p>Whether a statutory 14-day withdrawal right applies depends on the type of contract. Leisure services for a specified date may be exempt. Our agreed 24-hour cancellation right applies regardless and does not limit any mandatory statutory rights you may have.</p><p>Please first contact <a href="mailto:booking@didde-mie.com">booking@didde-mie.com</a> about a problem. If we cannot resolve it, eligible consumers may complain to the <a href="https://naevneneshus.dk/start-din-klage/center-for-klageloesning-og-forbrugerklagenaevnet/" target="_blank" rel="noopener noreferrer">Consumer Complaints Mediation Team, Nævnenes Hus, Toldboden 2, 8800 Viborg</a>. Eligibility depends, among other things, on the service and price.</p></section>
  <section><h2>8. Privacy and changes to these terms</h2><p>See our <a href="/privacy?lang=en">privacy policy</a> for booking data. The terms shown when you pay apply to that booking. Changes on this page apply to future bookings only.</p></section>
</>; }
