import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Privacy policy | TTD Studio", robots: { index: false, follow: false } };

export default async function PrivacyPage({ searchParams }: { searchParams: Promise<{ lang?: string }> }) {
  const language = (await searchParams).lang === "en" ? "en" : "da";
  return <LegalPage language={language} kind="privacy">{language === "da" ? <Danish /> : <English />}</LegalPage>;
}

function Danish() { return <>
  <p>Her kan du læse, hvordan TTD Studio behandler personoplysninger, når du besøger hjemmesiden, kontakter os eller bruger booking og events, når disse funktioner åbner.</p>
  <section><h2>1. Dataansvarlig</h2><p>[Indsæt den juridiske virksomhed eller de fælles dataansvarlige bag TTD Studio], CVR [indsæt CVR], [indsæt virksomhedsadresse]. Studiet ligger hos København Danser, Nygaardsvej 5a, 2. sal, 2100 København Ø. Skriv til <a href="mailto:booking@didde-mie.com">booking@didde-mie.com</a> om dine personoplysninger. Den juridiske identitet og den endelige kontaktadresse skal udfyldes før offentlig lancering.</p></section>
  <section><h2>2. Hvilke oplysninger og hvorfor?</h2><ul>
    <li><strong>Besøg på siden:</strong> Tekniske oplysninger som IP-adresse, tidspunkt og browser kan indgå i hostingens sikkerheds- og driftslogs. Formålet er at levere og beskytte siden. Grundlaget er vores legitime interesse i sikker drift, GDPR artikel 6, stk. 1, litra f.</li>
    <li><strong>Kontakt:</strong> Navn, e-mail, emne og besked bruges til at besvare din henvendelse. Grundlaget er artikel 6, stk. 1, litra b, når henvendelsen vedrører en mulig aftale, og ellers litra f om at kunne besvare henvendelser. Kontaktformularen sender din besked via vores server og mailudbyder.</li>
    <li><strong>Booking og betaling, når det åbner:</strong> Navn, e-mail, telefon, bookingtid, antal deltagere, formål, eventuelt virksomhedsnavn og dine valgfrie bemærkninger bruges til at kontrollere tilgængelighed, oprette og administrere bookingen, sende bekræftelse og kvittering, håndtere ændringer og refusioner samt verificere telefonnummeret. Grundlaget er artikel 6, stk. 1, litra b. Betalingsoplysninger håndteres af betalingsudbyderen; vi opbevarer ikke dit fulde kortnummer. Regnskabsoplysninger opbevares efter artikel 6, stk. 1, litra c.</li>
    <li><strong>Events, når billetsalget åbner:</strong> Oplysninger, du afgiver i billetkøbet, bruges til tilmelding, betaling og praktisk kommunikation om det konkrete event. De konkrete billetoplysninger fremgår af checkout.</li>
  </ul><p>Du behøver kun at give de oplysninger, der er nødvendige for at besvare din henvendelse eller gennemføre en booking. Undlad følsomme oplysninger i fritekstfelter. Uden de krævede bookingoplysninger kan vi ikke gennemføre bookingen.</p></section>
  <section><h2>3. Modtagere og overførsler</h2><p>Vi bruger leverandører til hosting, e-mail og, når booking åbner, pretix til ordrebehandling, Stripe til betaling og en SMS-udbyder til telefonverifikation. Adgang gives kun til relevante personer og leverandører. En planlagt studiekalender skal som udgangspunkt kun indeholde tidsrum og bookingreferencer, ikke kundens kontaktoplysninger. Leverandørernes konkrete roller, databehandleraftaler og eventuelle overførsler uden for EU/EØS kontrolleres før lancering. Hvis en overførsel finder sted, oplyser vi om grundlaget her.</p></section>
  <section><h2>4. Opbevaring</h2><p>Henvendelser slettes som udgangspunkt senest 12 måneder efter sidste relevante kontakt, medmindre de bliver en del af et kundeforhold eller en konkret tvist. Bookingoplysninger slettes eller anonymiseres, når de ikke længere er nødvendige for aftalen eller et konkret retskrav. Regnskabsmateriale opbevares i 5 år fra udgangen af det regnskabsår, det vedrører. Den konkrete frist for driftslogs og SMS-verifikationsdata fastsættes og indsættes før disse tjenester tages i brug.</p></section>
  <section><h2>5. Dine rettigheder</h2><p>Du kan bede om indsigt, berigtigelse, sletning, begrænsning og i relevante tilfælde dataportabilitet. Du kan gøre indsigelse mod behandling efter interesseafvejning. Rettighederne afhænger af den konkrete behandling, og lovpligtige oplysninger kan ikke altid slettes med det samme. Kontakt os på adressen ovenfor. Du kan også klage til <a href="https://www.datatilsynet.dk/borger/klage-til-datatilsynet" target="_blank" rel="noopener noreferrer">Datatilsynet</a>.</p></section>
  <section><h2>6. Cookies og eksternt indhold</h2><p>Booking-siden gemmer dit sprogvalg lokalt i browseren. En særskilt cookie- og teknologipolitik med en verificeret liste over teknologier, formål, udbydere og levetider offentliggøres før valgfri sporing eller offentlig checkout aktiveres. Teknologier, der kræver samtykke, må først bruges, når du aktivt har valgt dem, og du skal kunne ændre dit valg igen.</p></section>
  <section><h2>7. Ændringer</h2><p>Vi opdaterer denne politik, når funktioner eller leverandører ændres. Datoen øverst viser seneste revision.</p></section>
</>; }

function English() { return <>
  <p>This policy explains how TTD Studio processes personal data when you visit the site, contact us or use bookings and events once those features open.</p>
  <section><h2>1. Controller</h2><p>[Insert the legal business or joint controllers behind TTD Studio], Danish business registration no. (CVR) [insert CVR], [insert business address]. The studio is at København Danser, Nygaardsvej 5a, 2nd floor, 2100 Copenhagen Ø. For privacy requests, write to <a href="mailto:booking@didde-mie.com">booking@didde-mie.com</a>. Confirm the legal identity and final contact address before public launch.</p></section>
  <section><h2>2. Data and purposes</h2><ul>
    <li><strong>Site visits:</strong> Hosting security and operations logs may include IP address, time and browser information. The basis is our legitimate interest in running a secure site, GDPR Article 6(1)(f).</li>
    <li><strong>Contact:</strong> We use your name, email, subject and message to answer you. The basis is Article 6(1)(b) for a potential contract, or Article 6(1)(f) for other inquiries. The form sends your message through our server and email provider.</li>
    <li><strong>Bookings and payment, once available:</strong> We use name, email, phone, booked time, attendee count, purpose, optional company name and comments to check availability, administer the booking, send confirmation and receipt, handle changes and refunds, and verify the phone number. The basis is Article 6(1)(b). Our payment provider handles card details; we do not store your full card number. Accounting records are kept under Article 6(1)(c).</li>
    <li><strong>Events, once ticket sales open:</strong> Ticket checkout data is used for registration, payment and messages about that event. The checkout will show the specific information required.</li>
  </ul><p>Please do not put sensitive information in free-text fields. Without required booking details, we cannot complete a booking.</p></section>
  <section><h2>3. Recipients and transfers</h2><p>We use providers for hosting and email and, once bookings open, pretix for orders, Stripe for payments and an SMS provider for phone verification. Access is limited to relevant people and providers. The planned studio calendar should contain time slots and booking references, rather than customer contact details. Provider roles, processing agreements and any transfers outside the EU/EEA will be checked before launch and any transfer basis added here.</p></section>
  <section><h2>4. Retention</h2><p>We normally delete inquiries within 12 months of the last relevant contact unless they become part of a customer relationship or a specific dispute. Booking data is deleted or anonymised when no longer needed for the contract or a specific legal claim. Accounting records are kept for five years from the end of the relevant financial year. Retention for operational logs and SMS verification data must be confirmed before those services launch.</p></section>
  <section><h2>5. Your rights</h2><p>You may request access, correction, erasure, restriction and, where applicable, data portability. You may object to processing based on legitimate interests. These rights depend on the processing; legally required records cannot always be deleted immediately. Contact us at the address above. You may complain to the <a href="https://www.datatilsynet.dk/borger/klage-til-datatilsynet" target="_blank" rel="noopener noreferrer">Danish Data Protection Agency</a>.</p></section>
  <section><h2>6. Cookies and external content</h2><p>The booking site stores your language preference locally in your browser. A separate policy listing verified technologies, purposes, providers and lifetimes will be published before optional tracking or public checkout is enabled. Technologies requiring consent will only run after your active choice, which you must be able to change.</p></section>
  <section><h2>7. Changes</h2><p>We update this policy when features or providers change. The date above shows the latest revision.</p></section>
</>; }
