/** Exact displayed copy from deployed 8c79e511. Migration input only; never a website fallback. */
export const copy = {
  navigation: { introduction: 'Introduction', flowerDesktop: 'Spin the flower', flowerMobile: 'Spin or drag the flower', mainLabel: 'Main navigation', mobileLabel: 'Mobile navigation', work: 'Work', contact: 'Contact', booking: 'STUDIO BOOKING', mobileBooking: 'Studio booking', menu: 'MENU', wordmarkLabel: 'DD — Didde-Mie Lykke From, top of page' },
  footer: { owner: 'DD Production', privacy: 'PRIVACY POLICY', credit: 'Designed by', creditLabel: 'Memory(One)' },
  forms: { previewBefore: 'This is a visual preview. Forms are available on', previewAfter: '.', honeypot: 'Website' },
  contact: { nameLabel: 'YOUR NAME', namePlaceholder: 'Name', emailLabel: 'EMAIL ADDRESS', emailPlaceholder: 'name@example.com', subjectLabel: 'WHAT IS THIS ABOUT?', subjectPlaceholder: 'Choose a topic', dance: 'Dance / performance', choreography: 'Choreography', modelling: 'Modelling', brand_partnerships: 'Brand partnerships', other: 'Other', messageLabel: 'YOUR MESSAGE', messagePlaceholder: 'Tell DD about your inquiry…', validation: 'Complete or correct the highlighted fields before sending.', send: 'Send inquiry', sending: 'Sending…', success: 'Your message has been sent. Thank you!', error: 'Your message could not be sent. Please try again later.', privacyBefore: 'We use your details to reply.', privacyLink: 'Read the privacy policy', privacyAfter: '.' },
  newsletter: { intro: 'Sign up for my newsletter where I share updates on my work and dance videos!', emailLabel: 'EMAIL ADDRESS', emailPlaceholder: 'you@example.com', sending: 'SENDING…', send: 'SIGN UP', notice: 'DD Production will email you to confirm. Unsubscribe at any time.', privacy: 'Privacy policy', unsubscribe: 'Unsubscribe', success: "Check your inbox for a confirmation link. If you're already subscribed, you're all set.", error: "We couldn't start your signup right now. Please try again later." },
  reel: { canvasLabel: 'Dance video excerpts. Drag or use the left and right arrow keys to explore.', label: 'DD in motion', fallbackLabel: 'Dance video excerpts', sourceLabel: 'Tour source', explore: 'DRAG TO EXPLORE', previous: 'Previous dance clip', next: 'Next dance clip', play: 'Play dance clips', pause: 'Pause dance clips' },
  work: { imageError: 'Project image could not load', loading: 'Loading image for {title}', watch: 'Watch {title} video', region: 'Selected projects', galleryHint: 'CLICK AN IMAGE TO WATCH · OPENS YOUTUBE', previous: 'Previous project', next: 'Next project', listHint: 'SCROLL TO EXPLORE · {count} PROJECTS', scrollPrevious: 'Scroll to previous projects', scrollNext: 'Scroll to more projects' },
  unsubscribe: { emailLabel: 'EMAIL ADDRESS', sending: 'SENDING…', send: 'SEND UNSUBSCRIBE LINK', success: "If this address is subscribed, we'll email an unsubscribe link.", error: 'Please try later, or reply to a newsletter and ask to unsubscribe.' },
  marketing: { working: 'Working…', expired: 'This link has expired or has already been used.', error: 'We could not complete this request. Please try again later.', back: 'Back to DD' },
} as const;

export const pages = {
  confirm: { route: '/marketing/confirm', title: 'Email preferences | DD', heading: 'CONFIRM SIGNUP.', description: 'Confirm that you want my newsletter about my work and dance videos.', action: 'Confirm signup', success: 'Your signup is confirmed.', missing: 'Open the confirmation link from your email. If you have just signed in, reopen that link to continue.', recovery: 'Sign up again for a new confirmation link' },
  withdraw: { route: '/marketing/unsubscribe', title: 'Email preferences | DD', heading: 'UNSUBSCRIBE.', description: 'Stop my newsletter emails to this address.', action: 'Unsubscribe', success: 'You have been unsubscribed.', missing: 'Open the unsubscribe link from your email. If you have just signed in, reopen that link to continue.', recovery: 'Request a new unsubscribe link' },
  unsubscribe: { route: '/unsubscribe', title: 'Unsubscribe | DD', heading: 'UNSUBSCRIBE.', description: 'Enter your email to stop DD Production newsletter updates on my work and dance videos. You can also reply to any newsletter and ask to unsubscribe.', privacy: 'Privacy policy' },
} as const;
