/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../../tools/personal-sanity/schema.json
export type PersonalPage = {
  _id: string;
  _type: "personalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  route?:
    | "/privacy"
    | "/unsubscribe"
    | "/marketing/confirm"
    | "/marketing/unsubscribe";
  title?: string;
  heading?: string;
  description?: string;
  updatedLabel?: string;
  introduction?: PersonalRichText;
  sections?: Array<{
    heading?: string;
    body?: PersonalRichText;
    _type: "section";
    _key: string;
  }>;
  action?: string;
  success?: string;
  missing?: string;
  recovery?: string;
  privacy?: string;
  contactLabel?: string;
};

export type PersonalRichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    external?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type PersonalSettings = {
  _id: string;
  _type: "personalSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: {
    title?: string;
    description?: string;
    author?: string;
    socialTitle?: string;
    socialDescription?: string;
    socialImage?: PersonalImage;
  };
  branding?: {
    wordmark?: PersonalImage;
    contactMark?: PersonalImage;
    flowerMask?: PersonalImage;
    favicon?: PersonalImage;
    footerMark?: PersonalImage;
  };
  socialLinks?: Array<
    {
      _key: string;
    } & PersonalLink
  >;
  bookingLabel?: string;
  bookingHandle?: string;
  navigation?: PersonalNavigationCopy;
  footer?: PersonalFooterCopy;
  forms?: PersonalFormsCopy;
  contact?: PersonalContactCopy;
  newsletter?: PersonalNewsletterCopy;
  reel?: PersonalReelCopy;
  work?: PersonalWorkCopy;
  unsubscribe?: PersonalUnsubscribeCopy;
  marketing?: PersonalMarketingCopy;
};

export type PersonalMarketingCopy = {
  _type: "personalMarketingCopy";
  working?: string;
  expired?: string;
  error?: string;
  back?: string;
};

export type PersonalUnsubscribeCopy = {
  _type: "personalUnsubscribeCopy";
  emailLabel?: string;
  sending?: string;
  send?: string;
  success?: string;
  error?: string;
};

export type PersonalWorkCopy = {
  _type: "personalWorkCopy";
  imageError?: string;
  loading?: string;
  watch?: string;
  region?: string;
  galleryHint?: string;
  previous?: string;
  next?: string;
  listHint?: string;
  scrollPrevious?: string;
  scrollNext?: string;
};

export type PersonalReelCopy = {
  _type: "personalReelCopy";
  canvasLabel?: string;
  label?: string;
  fallbackLabel?: string;
  sourceLabel?: string;
  explore?: string;
  previous?: string;
  next?: string;
  play?: string;
  pause?: string;
};

export type PersonalNewsletterCopy = {
  _type: "personalNewsletterCopy";
  intro?: string;
  emailLabel?: string;
  emailPlaceholder?: string;
  sending?: string;
  send?: string;
  notice?: string;
  privacy?: string;
  unsubscribe?: string;
  success?: string;
  error?: string;
};

export type PersonalContactCopy = {
  _type: "personalContactCopy";
  nameLabel?: string;
  namePlaceholder?: string;
  emailLabel?: string;
  emailPlaceholder?: string;
  subjectLabel?: string;
  subjectPlaceholder?: string;
  dance?: string;
  choreography?: string;
  modelling?: string;
  brand_partnerships?: string;
  other?: string;
  messageLabel?: string;
  messagePlaceholder?: string;
  validation?: string;
  send?: string;
  sending?: string;
  success?: string;
  error?: string;
  privacyBefore?: string;
  privacyLink?: string;
  privacyAfter?: string;
};

export type PersonalFormsCopy = {
  _type: "personalFormsCopy";
  previewBefore?: string;
  previewAfter?: string;
  honeypot?: string;
};

export type PersonalFooterCopy = {
  _type: "personalFooterCopy";
  owner?: string;
  privacy?: string;
  credit?: string;
  creditLabel?: string;
};

export type PersonalNavigationCopy = {
  _type: "personalNavigationCopy";
  introduction?: string;
  flowerDesktop?: string;
  flowerMobile?: string;
  mainLabel?: string;
  mobileLabel?: string;
  work?: string;
  contact?: string;
  booking?: string;
  mobileBooking?: string;
  menu?: string;
  wordmarkLabel?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PersonalImage = {
  _type: "personalImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  credit?: string;
  frame?: PersonalFrame;
};

export type PersonalReelClipReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "personalReelClip";
};

export type PersonalWorkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "personalWork";
};

export type PersonalHome = {
  _id: string;
  _type: "personalHome";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    heading?: string;
    caption?: string;
    desktop?: PersonalImage;
    mobile?: PersonalImage;
  };
  introduction?: PersonalRichText;
  reelBio?: PersonalRichText;
  reelSource?: PersonalLink;
  reel?: Array<
    {
      _key: string;
    } & PersonalReelClipReference
  >;
  workHeading?: string;
  selectedWork?: Array<
    {
      _key: string;
    } & PersonalWorkReference
  >;
  contact?: {
    heading?: string;
    description?: string;
    desktop?: PersonalImage;
    mobile?: PersonalImage;
  };
  followHeading?: string;
};

export type PersonalLink = {
  _type: "personalLink";
  label?: string;
  url?: string;
  handle?: string;
};

export type PersonalWork = {
  _id: string;
  _type: "personalWork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: string;
  role?: string;
  description?: string;
  image?: PersonalImage;
  videoUrl?: string;
  legacyId?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type PersonalReelClip = {
  _id: string;
  _type: "personalReelClip";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  video?: {
    asset: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  poster?: PersonalImage;
  legacyId?: string;
};

export type PersonalFrame = {
  _type: "personalFrame";
  x?: number;
  y?: number;
  smallX?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | PersonalPage
  | PersonalRichText
  | PersonalSettings
  | PersonalMarketingCopy
  | PersonalUnsubscribeCopy
  | PersonalWorkCopy
  | PersonalReelCopy
  | PersonalNewsletterCopy
  | PersonalContactCopy
  | PersonalFormsCopy
  | PersonalFooterCopy
  | PersonalNavigationCopy
  | SanityImageAssetReference
  | PersonalImage
  | PersonalReelClipReference
  | PersonalWorkReference
  | PersonalHome
  | PersonalLink
  | PersonalWork
  | SanityFileAssetReference
  | PersonalReelClip
  | PersonalFrame
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../personal/src/cms/queries.ts
// Variable: PERSONAL_CONTENT_QUERY
// Query: {  "settings": *[_id == "personal-settings"][0]{_id,metadata{title,description,author,socialTitle,socialDescription,socialImage{alt,credit,frame,crop,hotspot,asset->{_id,url}}},branding{wordmark{alt,credit,frame,crop,hotspot,asset->{_id,url}},contactMark{alt,credit,frame,crop,hotspot,asset->{_id,url}},flowerMask{alt,credit,frame,crop,hotspot,asset->{_id,url}},favicon{alt,credit,frame,crop,hotspot,asset->{_id,url}},footerMark{alt,credit,frame,crop,hotspot,asset->{_id,url}}},socialLinks[]{_key,label,url,handle},bookingLabel,bookingHandle,navigation,footer,forms,contact,newsletter,reel,work,unsubscribe,marketing},  "home": *[_id == "personal-home"][0]{_id,hero{heading,caption,desktop{alt,credit,frame,crop,hotspot,asset->{_id,url}},mobile{alt,credit,frame,crop,hotspot,asset->{_id,url}}},introduction,reelBio,reelSource{label,url,handle},"reel":reel[]{_key,"clip":@->{_id,title,description,video{asset->{_id,url}},poster{alt,credit,frame,crop,hotspot,asset->{_id,url}}}}{"_key":_key,...clip},workHeading,"selectedWork":selectedWork[]{_key,"work":@->{_id,title,category,role,description,image{alt,credit,frame,crop,hotspot,asset->{_id,url}},videoUrl}}{"_key":_key,...work},contact{heading,description,desktop{alt,credit,frame,crop,hotspot,asset->{_id,url}},mobile{alt,credit,frame,crop,hotspot,asset->{_id,url}}},followHeading},  "pages": *[_type == "personalPage"] | order(route asc){_id,route,title,heading,description,updatedLabel,introduction,sections[]{_key,heading,body},action,success,missing,recovery,privacy,contactLabel}}
export type PERSONAL_CONTENT_QUERY_RESULT = {
  settings:
    | {
        _id: "personal-settings";
        metadata: null;
        branding: null;
        socialLinks: null;
        bookingLabel: null;
        bookingHandle: null;
        navigation: null;
        footer: null;
        forms: null;
        contact: null;
        newsletter: null;
        reel: null;
        work: null;
        unsubscribe: null;
        marketing: null;
      }
    | {
        _id: "personal-settings";
        metadata: {
          title: null;
          description: null;
          author: null;
          socialTitle: null;
          socialDescription: null;
          socialImage: null;
        } | null;
        branding: null;
        socialLinks: null;
        bookingLabel: null;
        bookingHandle: null;
        navigation: null;
        footer: null;
        forms: null;
        contact: null;
        newsletter: null;
        reel: null;
        work: null;
        unsubscribe: null;
        marketing: null;
      }
    | {
        _id: "personal-settings";
        metadata: null;
        branding: null;
        socialLinks: null;
        bookingLabel: null;
        bookingHandle: null;
        navigation: null;
        footer: null;
        forms: null;
        contact: {
          heading?: string;
          description?: string;
          desktop?: PersonalImage;
          mobile?: PersonalImage;
        } | null;
        newsletter: null;
        reel: Array<
          {
            _key: string;
          } & PersonalReelClipReference
        > | null;
        work: null;
        unsubscribe: null;
        marketing: null;
      }
    | {
        _id: "personal-settings";
        metadata: {
          title: string | null;
          description: string | null;
          author: string | null;
          socialTitle: string | null;
          socialDescription: string | null;
          socialImage: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
        } | null;
        branding: {
          wordmark: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
          contactMark: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
          flowerMask: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
          favicon: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
          footerMark: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
        } | null;
        socialLinks: Array<{
          _key: string;
          label: string | null;
          url: string | null;
          handle: string | null;
        }> | null;
        bookingLabel: string | null;
        bookingHandle: string | null;
        navigation: PersonalNavigationCopy | null;
        footer: PersonalFooterCopy | null;
        forms: PersonalFormsCopy | null;
        contact: PersonalContactCopy | null;
        newsletter: PersonalNewsletterCopy | null;
        reel: PersonalReelCopy | null;
        work: PersonalWorkCopy | null;
        unsubscribe: PersonalUnsubscribeCopy | null;
        marketing: PersonalMarketingCopy | null;
      }
    | null;
  home:
    | {
        _id: "personal-home";
        hero: null;
        introduction: null;
        reelBio: null;
        reelSource: null;
        reel: null;
        workHeading: null;
        selectedWork: null;
        contact: null;
        followHeading: null;
      }
    | {
        _id: "personal-home";
        hero: null;
        introduction: PersonalRichText | null;
        reelBio: null;
        reelSource: null;
        reel: null;
        workHeading: null;
        selectedWork: null;
        contact: null;
        followHeading: null;
      }
    | {
        _id: "personal-home";
        hero: null;
        introduction: null;
        reelBio: null;
        reelSource: null;
        reel: null;
        workHeading: null;
        selectedWork: null;
        contact: {
          heading: null;
          description: null;
          desktop: null;
          mobile: null;
        } | null;
        followHeading: null;
      }
    | {
        _id: "personal-home";
        hero: {
          heading: string | null;
          caption: string | null;
          desktop: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
          mobile: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
        } | null;
        introduction: PersonalRichText | null;
        reelBio: PersonalRichText | null;
        reelSource: {
          label: string | null;
          url: string | null;
          handle: string | null;
        } | null;
        reel: Array<{
          _key: string;
          _id: string;
          title: string | null;
          description: string | null;
          video: {
            asset: {
              _id: string;
              url: string | null;
            };
          } | null;
          poster: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
        }> | null;
        workHeading: string | null;
        selectedWork: Array<{
          _key: string;
          _id: string;
          title: string | null;
          category: string | null;
          role: string | null;
          description: string | null;
          image: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
          videoUrl: string | null;
        }> | null;
        contact: {
          heading: string | null;
          description: string | null;
          desktop: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
          mobile: {
            alt: string | null;
            credit: string | null;
            frame: PersonalFrame | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string | null;
            } | null;
          } | null;
        } | null;
        followHeading: string | null;
      }
    | null;
  pages: Array<{
    _id: string;
    route:
      | "/marketing/confirm"
      | "/marketing/unsubscribe"
      | "/privacy"
      | "/unsubscribe"
      | null;
    title: string | null;
    heading: string | null;
    description: string | null;
    updatedLabel: string | null;
    introduction: PersonalRichText | null;
    sections: Array<{
      _key: string;
      heading: string | null;
      body: PersonalRichText | null;
    }> | null;
    action: string | null;
    success: string | null;
    missing: string | null;
    recovery: string | null;
    privacy: string | null;
    contactLabel: string | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "settings": *[_id == "personal-settings"][0]{_id,metadata{title,description,author,socialTitle,socialDescription,socialImage{alt,credit,frame,crop,hotspot,asset->{_id,url}}},branding{wordmark{alt,credit,frame,crop,hotspot,asset->{_id,url}},contactMark{alt,credit,frame,crop,hotspot,asset->{_id,url}},flowerMask{alt,credit,frame,crop,hotspot,asset->{_id,url}},favicon{alt,credit,frame,crop,hotspot,asset->{_id,url}},footerMark{alt,credit,frame,crop,hotspot,asset->{_id,url}}},socialLinks[]{_key,label,url,handle},bookingLabel,bookingHandle,navigation,footer,forms,contact,newsletter,reel,work,unsubscribe,marketing},\n  "home": *[_id == "personal-home"][0]{_id,hero{heading,caption,desktop{alt,credit,frame,crop,hotspot,asset->{_id,url}},mobile{alt,credit,frame,crop,hotspot,asset->{_id,url}}},introduction,reelBio,reelSource{label,url,handle},"reel":reel[]{_key,"clip":@->{_id,title,description,video{asset->{_id,url}},poster{alt,credit,frame,crop,hotspot,asset->{_id,url}}}}{"_key":_key,...clip},workHeading,"selectedWork":selectedWork[]{_key,"work":@->{_id,title,category,role,description,image{alt,credit,frame,crop,hotspot,asset->{_id,url}},videoUrl}}{"_key":_key,...work},contact{heading,description,desktop{alt,credit,frame,crop,hotspot,asset->{_id,url}},mobile{alt,credit,frame,crop,hotspot,asset->{_id,url}}},followHeading},\n  "pages": *[_type == "personalPage"] | order(route asc){_id,route,title,heading,description,updatedLabel,introduction,sections[]{_key,heading,body},action,success,missing,recovery,privacy,contactLabel}\n}': PERSONAL_CONTENT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
