import type {Fetcher} from '@cloudflare/workers-types';
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=/home/megawatts/Projects/DD_website/dd-platform-personal-sanity/apps/personal/wrangler.preview.jsonc --include-runtime=false --strict-vars=false --env-interface=PreviewEnv /home/megawatts/Projects/DD_website/dd-platform-personal-sanity/apps/personal/worker-configuration.d.ts` (hash: 14e95367fb69e80a8bcba53e3ea7de01)
interface __BaseEnv_PreviewEnv {
	ASSETS: Fetcher;
	ACCESS_ISSUER: string;
	ACCESS_AUDIENCE: string;
	SANITY_PREVIEW_READ_TOKEN: string;
	PREVIEW_SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/preview/worker");
	}
	interface Env extends __BaseEnv_PreviewEnv {}
}
interface PreviewEnv extends __BaseEnv_PreviewEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_ISSUER" | "ACCESS_AUDIENCE" | "SANITY_PREVIEW_READ_TOKEN" | "PREVIEW_SESSION_SECRET">> {}
}

export type {PreviewEnv};
